[package]
name = "zettelmaschine"
version = "0.1.0"
authors = ["Vincent Rolfs <vincent.rolfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
